### PR TITLE
Add Web Demo & Docker environment 

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @williamyang1991! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! View it here: https://replicate.com/williamyang1991/gp-unit. The docker file can be found under the tab ‘run model with docker’. 

Do claim the page so you can own the page, customise the Example gallery as you like, push any future update to the web demo, and we'll feature it on our website and tweet about it too. You can find the 'Claim this model' button on the top of the page ~ 

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by williamyang1991** [comment]
Thank you for this fancy web demo!

**Comment by williamyang1991** [comment]
Hi @chenxwh,  I have played with this interesting web demo. 
And I find if I do not upload any style image, it will report 
`1 validation error for Input style field required (type=value_error.missing)`
I wonder if we can add a default value to the Input `style` like `default="None",` 
and if `str(style)=="None"`, the code will switch to latent-guided translation instead of exemplar-guided transaltion. 

https://github.com/williamyang1991/GP-UNIT/blob/a873d5ec3c23c0f2182617fdc9151b4f022d6a52/predict.py#L48-L50

Actually, I have tried it (https://github.com/williamyang1991/GP-UNIT/commit/965ebd3ca0d9f89913c41a94eeec315398f3ade8)
but this simple modification seems not work. It will still report 
`1 validation error for Input style field required (type=value_error.missing)`

**Comment by chenxwh** [comment]
Hi yes! The PR is just an example how to get started to deploy your model on replicate, feel free to update it however you like. For optional input I see that you have set it to a sting ’None’, instead just None should work :)

**Comment by williamyang1991** [comment]
Thank you for your reply, @chenxwh.
I have modify "None" to None
https://github.com/williamyang1991/GP-UNIT/blob/0f132498c690c07aa034343346c6efc3df3f9455/predict.py#L49-L52

But  It will still report
`1 validation error for Input style field required (type=value_error.missing)`

I try to modify the description like removing the `.` from `Input style image, it will be resized to 256.`, 
but after I commit changes, I find the web demo does not make the corresponding changes.
I wonder if it requires some steps to update the web demo after I update the predict.py?

Sorry I'm not familar with Cog. It will be really helpful if you can tell me these steps.

**Comment by chenxwh** [comment]
Yes you will need to install cog first, then deploy changes on the website with ‘cog push r8.im/williamyang1991/gp-unit <https://replicate.com/aidmin/models/model/534/change/>’. This document should walk you through the procedure:https://github.com/replicate/cog/blob/4591e1c20d0e792b8ff76afb30966af23a687ee6/docs/getting-started.md <https://github.com/replicate/cog/blob/4591e1c20d0e792b8ff76afb30966af23a687ee6/docs/getting-started.md>  :)

None will work for optional parameters, not sure how you tested it locally, but if you push to the website you will see. Here is a similar example https://github.com/chenxwh/maskgit/blob/replicate/predict.py#L5 <https://github.com/chenxwh/maskgit/blob/replicate/predict.py#L5>. Hope it helps!

**Comment by williamyang1991** [comment]
@chenxwh thank you for your quick reply. I will study it.

**Comment by zeke** [comment]
Hi @williamyang1991  👋🏼 

I'm Zeke from the @replicate team.

This model is really impressive!

I just wanted to let you know that the arXiv.org website now includes a link to your model on Replicate.

See the "Demos" tab at the bottom of the page here: https://arxiv.org/abs/2204.03641

Screen Shot 2022-05-02 at 2 46 49 PM

**Comment by williamyang1991** [comment]
@zeke Thank you!

**Pull request merged**
